/*
 * cfgtest.c -- the kboot.cfg parser, on a host.
 *
 * The parser is the loader's most dangerous quiet component: every field it
 * gets wrong produces a clean boot of the wrong thing.  A wrong partition base
 * mounts a filesystem at the wrong blocks; a wrong `default' boots the other
 * kernel; a `timeout' misread as present starts a countdown nobody asked for.
 * None of those announce themselves.
 *
 * So the cases below are mostly NOT the happy path.  The happy path is one
 * test; the rest are the malformed, the truncated, the out-of-range and the
 * unknown-keyword lines that a real disk eventually produces.
 */
#include <stdio.h>
#include <string.h>
#include "../src/kboot.h"
#include <bootinfo.h>

/* The shipped sample, as reached from tests/.  The makefile names it. */
#ifndef CFGSAMPLE
#define CFGSAMPLE "../cfg/kboot.cfg.sample"
#endif

extern int nparts;			/* cfg.c: `part' lines accepted */
extern struct bootinfo bi;	/* cfg.c: the layout cfglayout() builds */

static int fails;

#define OK(what, got, want) check(what, (long)(got), (long)(want))

static void
check(char *what, long got, long want)
{
	if (got != want) {
		printf("  FAIL %-34s got %ld want %ld\n", what, got, want);
		fails++;
	}
}

static void
oks(char *what, char *got, char *want)
{
	if (strcmp(got, want) != 0) {
		printf("  FAIL %-34s got \"%s\" want \"%s\"\n", what, got, want);
		fails++;
	}
}

/* Feed the parser a config exactly as cfgread() would: the text, then zeros
 * out to CFGMAX, because a short file's unread blocks are holes and read as
 * zeros.  Tests that skip the zero tail are testing a file shape the loader
 * never sees. */
static void
parse(char *text)
{
	memset(cfg, 0, CFGMAX);
	memcpy(cfg, text, strlen(text) > CFGMAX ? CFGMAX : strlen(text));
	cfglen = CFGMAX;
	gcyl = 612; gheads = 4; gspt = 17; gprecomp = 128;
	cfgparse();
}

static void
t_basic()
{
	printf("a real generated config\n");
	parse("# kboot.cfg -- generated by mkimage.py; do not edit by hand.\n"
	      "geom 704 7 17 352\n"
	      "part 0 0 136\n"
	      "part 4 136 10200\n"
	      "swap 3 2904 7000\n"
	      "os OpenCoherent-3.5 136 coherent part\n"
	      "os CPM-8000 38008 cpm.sys\n");
	OK("nos", nos, 2);
	OK("gcyl", gcyl, 704);
	OK("gheads", gheads, 7);
	OK("gspt", gspt, 17);
	OK("gprecomp", gprecomp, 352);
	oks("label 0", oslist[0].label, "OpenCoherent-3.5");
	OK("base 0", oslist[0].base, 136);
	oks("file 0", oslist[0].file, "coherent");
	OK("wantbi 0", oslist[0].wantbi, 1);
	oks("label 1", oslist[1].label, "CPM-8000");
	OK("base 1", oslist[1].base, 38008);
	oks("file 1", oslist[1].file, "cpm.sys");
	OK("wantbi 1", oslist[1].wantbi, 0);
	OK("timeout absent", cfgwait, 0);
	OK("default absent", cfgdflt, 0);
}

static void
t_v2keys()
{
	printf("the v2 keys\n");
	parse("timeout 7\ndefault 3\n"
	      "os a 100 k1\nos b 200 k2\nos c 300 k3\n");
	OK("timeout", cfgwait, 7);
	OK("default", cfgdflt, 3);
	OK("nos", nos, 3);
	OK("base 2", oslist[2].base, 300);

	/* An OLD config through a NEW loader: every new key has a default, so
	 * absence must land on "wait forever", never on some built-in wait. */
	parse("os a 100 k1\nos b 200 k2\n");
	OK("no timeout key -> 0", cfgwait, 0);
	OK("no default key -> 0", cfgdflt, 0);

	/* A NEW config through this loader with keys it will not know: unknown
	 * keywords are ignored, which is the compatibility rule in both
	 * directions and is worth a test rather than a comment. */
	parse("timeout 4\nquorum yes please\nsum a3f1\nos a 100 k1\n");
	OK("unknown keys ignored: timeout", cfgwait, 4);
	OK("unknown keys ignored: nos", nos, 1);
}

static void
t_truncation()
{
	printf("truncation and overlong fields\n");
	/* A label longer than LBLSZ is truncated, not overrun.  This is the one
	 * that would corrupt the next entry in the array rather than misbehave
	 * visibly. */
	parse("os 0123456789012345678901234567890 100 k\n");
	OK("label truncated to LBLSZ-1", (long)strlen(oslist[0].label), LBLSZ - 1);
	oks("label content", oslist[0].label, "0123456789012345678");

	parse("os a 100 0123456789012345678901234\n");
	OK("file truncated to DIRSIZ-1", (long)strlen(oslist[0].file), DIRSIZ - 1);

	/* A file cut off mid-line at the buffer edge: the surviving fragment
	 * parses, and what matters is that the HALF line does not become a
	 * whole entry with a garbage base. */
	parse("os good 136 coherent\nos trunc");
	OK("half an os line is not an entry", nos, 1);
	oks("the whole one survived", oslist[0].label, "good");
}

static void
t_malformed()
{
	printf("malformed lines\n");
	parse("geom 704 7\nos a 100 k\n");
	OK("short geom line ignored", gcyl, 612);
	OK("...and the rest still parses", nos, 1);

	parse("os a 100\nos b 200 k2\n");
	OK("short os line ignored", nos, 1);
	oks("the good one is entry 0", oslist[0].label, "b");

	parse("os a xyz k\n");
	OK("non-numeric base reads 0", oslist[0].base, 0);

	parse("part 99 1 2\npart 3 500 600\nos a 1 k part\n");
	cfglayout(0);
	OK("out-of-range slot dropped", nparts, 1);

	/* MAXOS: entries past it are dropped, and the ones kept are the FIRST
	 * ones -- a later line must not overwrite an earlier entry. */
	parse("os a 1 k\nos b 2 k\nos c 3 k\nos d 4 k\nos e 5 k\n"
	      "os f 6 k\nos g 7 k\nos h 8 k\nos i 9 k\nos j 10 k\n");
	OK("capped at MAXOS", nos, MAXOS);
	oks("first entry kept", oslist[0].label, "a");
	oks("last kept entry", oslist[MAXOS-1].label, "h");
}

static void
t_comments()
{
	printf("comments and whitespace\n");
	parse("  \t geom 704 7 17 352   \n"
	      "os a 100 k # trailing comment\n"
	      "# whole line\n"
	      "\n"
	      "\tos b 200 k2\r\n");
	OK("leading whitespace", gcyl, 704);
	OK("blank + comment lines", nos, 2);
	oks("CRLF did not join the label", oslist[1].file, "k2");

	/* A comment character inside a token ends it.  Worth pinning: it is the
	 * difference between a kernel called "k" and one called "k#2". */
	parse("os a 100 k#2\n");
	oks("# ends a token", oslist[0].file, "k");
}

/* Every `part' slot, and the swap extent, that entry `k' would be handed. */
static void
layout(k) int k;
{
	cfglayout(k);
}

static void
t_layout()
{
	printf("per-entry layouts\n");

	/* AN OLD CONFIG: part/swap before any `os' line are the global layout,
	 * and every entry takes it.  This is the shape every generated config
	 * has today, and it must not move. */
	parse("part 0 0 136\npart 4 136 10200\nswap 3 2904 7000\n"
	      "os A 136 coherent part\nos B 900 coherent part\n");
	OK("no entry claims its own layout", oslist[0].lay, LAYGLOB);
	OK("nor the second", oslist[1].lay, LAYGLOB);
	layout(0);
	OK("global: hd4 start", bi.bi_part[4].bstart, 136);
	OK("global: hd4 blocks", bi.bi_part[4].bcount, 10200);
	OK("global: swapdev", bi.bi_swapdev, 3);
	OK("global: swapbot", bi.bi_swapbot, 2904);
	OK("global: nparts", nparts, 2);
	layout(1);
	OK("the second entry gets the same", bi.bi_part[4].bcount, 10200);
	OK("...and the same swap", bi.bi_swapbot, 2904);

	/* TWO SYSTEMS, TWO LAYOUTS.  Lines after an `os' line belong to that
	 * entry; the entry before it still takes the globals. */
	parse("part 4 136 10200\nswap 3 2904 7000\n"
	      "os A 136 coherent part\n"
	      "os B 75520 coherent part\n"
	      "part 4 75520 10336\npart 2 85856 4000\n"
	      "swap 2 1000 3000\n");
	OK("A takes the globals", oslist[0].lay, LAYGLOB);
	OK("B owns its own", oslist[1].lay, 1);
	layout(0);
	OK("A: hd4 start", bi.bi_part[4].bstart, 136);
	OK("A: hd4 blocks", bi.bi_part[4].bcount, 10200);
	OK("A: hd2 unused", bi.bi_part[2].bcount, 0);
	OK("A: swapdev", bi.bi_swapdev, 3);
	OK("A: swaptop", bi.bi_swaptop, 7000);
	OK("A: nparts", nparts, 1);
	layout(1);
	OK("B: hd4 start", bi.bi_part[4].bstart, 75520);
	OK("B: hd4 blocks", bi.bi_part[4].bcount, 10336);
	OK("B: hd2 blocks", bi.bi_part[2].bcount, 4000);
	OK("B: swapdev", bi.bi_swapdev, 2);
	OK("B: swapbot", bi.bi_swapbot, 1000);
	OK("B: nparts", nparts, 2);
	/* And back again: no slot of B's survives into A's table. */
	layout(0);
	OK("A again: hd2 still unused", bi.bi_part[2].bcount, 0);
	OK("A again: swapdev", bi.bi_swapdev, 3);

	/* NOTHING LEAKS IN.  An entry that declares any layout line of its own
	 * takes none of the global one -- including the swap extent, which is
	 * the field most likely to be silently wrong. */
	parse("part 4 136 10200\nswap 3 2904 7000\n"
	      "os A 136 coherent part\n"
	      "os B 75520 coherent part\npart 4 75520 10336\n");
	layout(1);
	OK("own table, no swap declared", bi.bi_swaptop, 0);
	OK("...and no swapdev", bi.bi_swapdev, 0);
	OK("...and none of A's slots", nparts, 1);

	/* A swap line alone is a layout of its own too, and it takes no
	 * partition table with it. */
	parse("part 4 136 10200\nswap 3 2904 7000\n"
	      "os A 136 coherent part\nos B 900 coherent part\nswap 5 10 20\n");
	layout(1);
	OK("own swap: slot", bi.bi_swapdev, 5);
	OK("own swap: no table", nparts, 0);

	/* An entry with no table flag is not affected by any of this: cfg.c
	 * records the layout, bmain.c decides whether to hand one over. */
	parse("part 4 136 10200\nos CPM 58624 cpm.sys\n");
	OK("no `part' flag", oslist[0].wantbi, 0);
	OK("and no layout of its own", oslist[0].lay, LAYGLOB);

	/* Layout lines under an `os' line DROPPED for MAXOS must not be read
	 * as some kept entry's.  The 9th os line owns the part line below it,
	 * and entry 0 must still see the globals. */
	parse("part 4 136 10200\n"
	      "os a 1 k part\nos b 2 k\nos c 3 k\nos d 4 k\nos e 5 k\n"
	      "os f 6 k\nos g 7 k\nos h 8 k\n"
	      "os i 9 k\npart 4 999 999\n");
	OK("capped at MAXOS", nos, MAXOS);
	layout(0);
	OK("entry 0 kept the globals", bi.bi_part[4].bstart, 136);
	OK("...not the dropped entry's", bi.bi_part[4].bcount, 10200);
}

/*
 * Named boot flags.  The names are the CONFIG's -- a `bflag' line pairs a word
 * with the bit of the kernel that entry boots -- so the cases that matter are
 * the ones where a name resolves to the WRONG bit or to none at all: those
 * boot a system that looks exactly like the one that was asked for.
 */
static void
t_flags()
{
	char fb[FLGSZ];

	printf("named boot flags\n");
	parse("bflag SINGLE 1\nbflag QUICK 16\n"
	      "os A 136 coherent part\nflags SINGLE\n"
	      "os B 900 coherent\nflags QUICK SINGLE\n");
	OK("nos", nos, 2);
	OK("a named flag reaches bflags", oslist[0].bflags, 1);
	OK("...and is not a refusal", oslist[0].badflg, 0);
	OK("two names on one line are OR'd", oslist[1].bflags, 17);
	OK("no orphan `flags' line", cfgflgerr, 0);
	bflabel(0, fb, FLGSZ);
	oks("the name is printable again", fb, "SINGLE");
	bflabel(1, fb, FLGSZ);
	oks("both names, in `bflag' order", fb, "SINGLE QUICK");

	/* AN UNKNOWN NAME IS REFUSED.  The bit cannot be guessed, and a boot
	 * with the flag dropped is the failure this key exists to prevent. */
	parse("bflag SINGLE 1\nos A 1 k\nflags SNGLE\n");
	OK("an unknown name refuses the entry", oslist[0].badflg, 1);
	OK("...and sets no bit", oslist[0].bflags, 0);

	/* An unknown KEYWORD is still ignored -- the compatibility rule -- and
	 * that is a different thing from an unknown name inside a keyword this
	 * loader implements. */
	parse("bflag SINGLE 1\nos A 1 k\nflagz SNGLE\nquorum yes\nflags SINGLE\n");
	OK("unknown keywords stay ignored", oslist[0].badflg, 0);
	OK("...and the known one still ran", oslist[0].bflags, 1);

	/* PER-ENTRY VOCABULARIES: two kernels need not agree on a bit, so the
	 * same word must be able to mean different bits in one file. */
	parse("bflag SINGLE 1\n"
	      "os A 1 k\nflags SINGLE\n"
	      "os B 2 k\nbflag SINGLE 4\nflags SINGLE\n");
	OK("A takes the default vocabulary", oslist[0].bflags, 1);
	OK("B takes its own", oslist[1].bflags, 4);

	/* ALL OR NOTHING, as with `part' and `swap': an entry that defines any
	 * name of its own takes none of the default names.  Half a vocabulary
	 * is another kernel's bit under this kernel's word. */
	parse("bflag SINGLE 1\nbflag QUICK 16\n"
	      "os A 1 k\nbflag SINGLE 4\nflags QUICK\n");
	OK("no default name leaks in", oslist[0].bflags, 0);
	OK("...it is refused instead", oslist[0].badflg, 1);

	/* A `flags' line above the first `os' line owns nothing.  It sets no
	 * entry's flags and says so rather than looking obeyed. */
	parse("bflag SINGLE 1\nflags SINGLE\nos A 1 k\n");
	OK("orphan `flags' line is reported", cfgflgerr, 1);
	OK("...and set nothing", oslist[0].bflags, 0);

	/* Five tokens a line are kept, so a sixth name would be dropped
	 * unseen.  Refused, not truncated. */
	parse("bflag a 1\nbflag b 2\nbflag c 4\nbflag d 8\nbflag e 16\n"
	      "os A 1 k\nflags a b c d e\n");
	OK("more names than a line holds", oslist[0].badflg, 1);
	parse("bflag a 1\nbflag b 2\nbflag c 4\nbflag d 8\n"
	      "os A 1 k\nflags a b c d\n");
	OK("a full line is fine", oslist[0].bflags, 15);
	OK("...and not a refusal", oslist[0].badflg, 0);

	/* A name worth no bits is not a name: `flags' naming it would set
	 * nothing and read as obeyed. */
	parse("bflag NONE 0\nos A 1 k\nflags NONE\n");
	OK("a zero-bit name is refused", oslist[0].badflg, 1);

	/* A config from before this key: no flags, no refusals, no fault. */
	parse("part 4 136 10200\nos A 136 coherent part\nos B 900 coherent\n");
	OK("no `flags' key -> no flags", oslist[0].bflags, 0);
	OK("...no refusal", oslist[0].badflg, 0);
	OK("...and nothing to report", cfgflgerr, 0);
	bflabel(0, fb, FLGSZ);
	oks("...and nothing to show", fb, "");
}

/*
 * `system' blocks.  The case they exist for is one OS with two entries --
 * multi-user and single-user -- times two OSes: four entries, two layouts,
 * two vocabularies, each written once.  The dangerous half is the vocabulary:
 * the two systems give SINGLE DIFFERENT bits, so a name resolved against the
 * wrong block sets a flag the kernel that boots does not mean by it, and the
 * boot looks exactly like the one that was asked for.
 */
static char four[] =
	"geom 1024 7 17 512\n"
	"system 3.5\n"
	"part 0 0 136\n"
	"part 4 136 10200\n"
	"swap 3 2904 7000\n"
	"bflag SINGLE 1\n"
	"os OpenCoherent-3.5 136 coherent part\n"
	"os OC-3.5-single 136 coherent part\n"
	"flags SINGLE\n"
	"system 0.8\n"
	"part 0 60000 136\n"
	"part 4 60136 10200\n"
	"swap 4 1000 5000\n"
	"bflag SINGLE 4\n"
	"os OpenCoherent-0.8 60000 coherent part\n"
	"os OC-0.8-single 60000 coherent part\n"
	"flags SINGLE\n";

static void
t_system()
{
	char fb[FLGSZ];

	printf("`system' blocks\n");
	parse(four);
	OK("nos", nos, 4);
	oks("label 0", oslist[0].label, "OpenCoherent-3.5");
	oks("label 3", oslist[3].label, "OC-0.8-single");
	OK("geom survives above the blocks", gcyl, 1024);

	/* Both entries of a system name that system, not themselves and not
	 * the global scope: the layout is written once. */
	OK("3.5 multi -> block 0", oslist[0].lay, LAYSYS(0));
	OK("3.5 single -> block 0", oslist[1].lay, LAYSYS(0));
	OK("0.8 multi -> block 1", oslist[2].lay, LAYSYS(1));
	OK("0.8 single -> block 1", oslist[3].lay, LAYSYS(1));
	OK("...and the vocabularies too", oslist[0].voc, LAYSYS(0));
	OK("...both of them", oslist[3].voc, LAYSYS(1));

	cfglayout(0);
	OK("3.5: hd0 start", bi.bi_part[0].bstart, 0);
	OK("3.5: hd4 start", bi.bi_part[4].bstart, 136);
	OK("3.5: hd4 blocks", bi.bi_part[4].bcount, 10200);
	OK("3.5: swapdev", bi.bi_swapdev, 3);
	OK("3.5: swapbot", bi.bi_swapbot, 2904);
	OK("3.5: nparts", nparts, 2);
	cfglayout(1);
	OK("3.5 single: same table", bi.bi_part[4].bstart, 136);
	OK("3.5 single: same swap", bi.bi_swapbot, 2904);
	cfglayout(2);
	OK("0.8: hd0 start", bi.bi_part[0].bstart, 60000);
	OK("0.8: hd4 start", bi.bi_part[4].bstart, 60136);
	OK("0.8: swapdev", bi.bi_swapdev, 4);
	OK("0.8: swapbot", bi.bi_swapbot, 1000);
	OK("0.8: swaptop", bi.bi_swaptop, 5000);
	OK("0.8: nparts", nparts, 2);
	cfglayout(3);
	OK("0.8 single: same table", bi.bi_part[4].bstart, 60136);
	OK("0.8 single: same swap", bi.bi_swapdev, 4);
	/* And back: no slot of one system's table survives into the other's. */
	cfglayout(0);
	OK("3.5 again: hd0 start", bi.bi_part[0].bstart, 0);
	OK("3.5 again: swapdev", bi.bi_swapdev, 3);

	/* THE ASSERTION THIS GRAMMAR EXISTS FOR: one word, two bits, and each
	 * entry must read it against its own system. */
	OK("SINGLE is bit 1 on 3.5", bfbit(0, -1, "SINGLE"), 1);
	OK("...on both 3.5 entries", bfbit(1, -1, "SINGLE"), 1);
	OK("SINGLE is bit 4 on 0.8", bfbit(2, -1, "SINGLE"), 4);
	OK("...on both 0.8 entries", bfbit(3, -1, "SINGLE"), 4);
	OK("3.5 multi carries none", oslist[0].bflags, 0);
	OK("3.5 single carries bit 1", oslist[1].bflags, 1);
	OK("0.8 multi carries none", oslist[2].bflags, 0);
	OK("0.8 single carries bit 4", oslist[3].bflags, 4);
	OK("nothing is refused", oslist[1].badflg + oslist[3].badflg, 0);
	OK("no orphan `flags' line", cfgflgerr, 0);
	bflabel(1, fb, FLGSZ);
	oks("3.5 single names it", fb, "SINGLE");
	bflabel(3, fb, FLGSZ);
	oks("0.8 single names it", fb, "SINGLE");

	/* A file with no `system' line at all is what it was before this key
	 * existed: the lines above the first `os' line are every entry's. */
	parse("part 4 136 10200\nswap 3 2904 7000\nbflag SINGLE 1\n"
	      "os A 136 coherent part\nflags SINGLE\nos B 900 coherent part\n");
	OK("no block: global layout", oslist[0].lay, LAYGLOB);
	OK("no block: global vocabulary", oslist[1].voc, LAYGLOB);
	OK("no block: the name still resolves", oslist[0].bflags, 1);
	cfglayout(1);
	OK("no block: B gets the globals", bi.bi_part[4].bcount, 10200);

	/* ALL OR NOTHING still, one level down: an entry with a layout line of
	 * its own takes nothing from its system, swap included. */
	parse("system s\npart 4 136 10200\nswap 3 2904 7000\nbflag SINGLE 1\n"
	      "os A 1 k part\nos B 2 k part\npart 4 999 8\n");
	OK("B owns its own layout", oslist[1].lay, 1);
	cfglayout(1);
	OK("B: its own slot", bi.bi_part[4].bcount, 8);
	OK("B: and no swap", bi.bi_swapdev, 0);
	OK("B: none of the block's slots", nparts, 1);
	cfglayout(0);
	OK("A still has the block's", bi.bi_part[4].bcount, 10200);
	/* Its vocabulary is a separate question from its layout. */
	OK("B keeps the block's names", bfbit(1, -1, "SINGLE"), 1);

	/* A block that declares nothing of a kind falls through to the global
	 * lines, the way an entry does: the nearest scope that named anything
	 * wins, and an empty block is not a scope that named something. */
	parse("part 4 136 10200\nbflag SINGLE 1\n"
	      "system s\nos A 1 k part\nflags SINGLE\n");
	OK("empty block: global layout", oslist[0].lay, LAYGLOB);
	OK("empty block: global names", oslist[0].bflags, 1);
	cfglayout(0);
	OK("empty block: the global table", bi.bi_part[4].bcount, 10200);

	/* A block that declares a table but no names takes the global names,
	 * and its own table: the two scopes are resolved separately. */
	parse("bflag SINGLE 1\npart 4 136 10200\n"
	      "system s\npart 4 900 90\nos A 1 k part\nflags SINGLE\n");
	OK("own table, global names", oslist[0].bflags, 1);
	cfglayout(0);
	OK("...and the block's table", bi.bi_part[4].bcount, 90);

	/* A `flags' line inside a block but above its first `os' line owns
	 * nothing: a block is not an entry and cannot carry flags for one. */
	parse("bflag SINGLE 1\nsystem s\nflags SINGLE\nos A 1 k\n");
	OK("`flags' in a block header is reported", cfgflgerr, 1);
	OK("...and set nothing", oslist[0].bflags, 0);

	/* A name is read against the vocabulary its entry ENDS UP with,
	 * whichever side of the `flags' line the `bflag' line was written. */
	parse("bflag SINGLE 1\nos A 1 k\nflags SINGLE\nbflag SINGLE 4\n");
	OK("`bflag' after `flags' still counts", oslist[0].bflags, 4);
	OK("...and is not a refusal", oslist[0].badflg, 0);

	/* An unknown keyword is still ignored, and `system' does not make one
	 * of a word that merely starts the same way. */
	parse("system s\nsystemd yes\npart 4 136 10200\n"
	      "os A 1 k part\n");
	OK("`systemd' is not `system'", oslist[0].lay, LAYSYS(0));
	cfglayout(0);
	OK("...and its line was ignored", bi.bi_part[4].bcount, 10200);
}

/*
 * The shipped sample, through the real parser.  cfg/kboot.cfg.sample is the
 * file a user copies onto the disk verbatim, so two things about it are the
 * loader's business: it must fit the CFGMAX the loader reads, comments
 * included, and the layout it describes must be the one the parser builds
 * from it.  Nothing else in this repository reads that file, so without this
 * it can drift from the grammar silently.
 */
static void
t_sample()
{
	static char raw[CFGMAX * 8], bare[CFGMAX * 8];
	FILE *f;
	char fb[FLGSZ];
	int n, i, j, incomment;

	printf("the shipped sample config\n");
	f = fopen(CFGSAMPLE, "r");
	if (f == 0) {
		printf("  FAIL cannot open %s\n", CFGSAMPLE);
		fails++;
		return;
	}
	n = fread(raw, 1, sizeof raw - 1, f);
	fclose(f);
	raw[n] = '\0';
	OK("sample is not empty", n > 0, 1);
	OK("sample fits CFGMAX untruncated", n <= CFGMAX, 1);

	parse(raw);
	OK("geom cyl", gcyl, 1024);
	OK("geom heads", gheads, 7);
	OK("geom spt", gspt, 17);
	OK("geom precomp", gprecomp, 512);
	OK("nos", nos, 2);
	oks("label 0", oslist[0].label, "OpenCoherent-3.5");
	OK("base 0", oslist[0].base, 136);
	oks("file 0", oslist[0].file, "coherent");
	OK("entry 0 takes the table", oslist[0].wantbi, 1);
	oks("label 1", oslist[1].label, "CPM-8000");
	OK("entry 1 takes none", oslist[1].wantbi, 0);
	OK("timeout", cfgwait, 5);
	OK("default", cfgdflt, 1);
	OK("no orphan `flags' line", cfgflgerr, 0);
	OK("no entry is refused", oslist[0].badflg + oslist[1].badflg, 0);
	/* The sample's worked example of `flags': the name must reach the bit
	 * its `bflag' line gives it and land in the entry's flag word, or the
	 * demonstration is a line that boots nothing different. */
	OK("its `bflag' name resolves", bfbit(0, -1, "SINGLE"), 1);
	OK("`flags SINGLE' reaches bflags", oslist[0].bflags, 1);
	OK("and only that entry's", oslist[1].bflags, 0);
	bflabel(0, fb, FLGSZ);
	oks("the menu can name it", fb, "SINGLE");

	/* Both entries inherit the default layout, and it is the one the
	 * sample's `part' and `swap' lines spell out. */
	OK("entry 0 inherits", oslist[0].lay, LAYGLOB);
	OK("entry 1 inherits", oslist[1].lay, LAYGLOB);
	cfglayout(0);
	OK("hd0 start", bi.bi_part[0].bstart, 0);
	OK("hd0 blocks", bi.bi_part[0].bcount, 136);
	OK("hd1 start", bi.bi_part[1].bstart, 10336);
	OK("hd3 blocks", bi.bi_part[3].bcount, 7000);
	OK("hd4 start", bi.bi_part[4].bstart, 136);
	OK("hd4 blocks", bi.bi_part[4].bcount, 10200);
	OK("hd15 blocks", bi.bi_part[15].bcount, 121856);
	OK("slots named", nparts, 5);
	OK("swapdev", bi.bi_swapdev, 3);
	OK("swapbot", bi.bi_swapbot, 2904);
	OK("swaptop", bi.bi_swaptop, 7000);

	/* The comments carry no configuration: stripped of them, the same
	 * file parses to the same layout, and what is left is what the disk
	 * would still have to hold if every comment were deleted. */
	j = 0;
	incomment = 0;
	for (i = 0; i < n; i++) {
		if (raw[i] == '#')
			incomment = 1;
		if (raw[i] == '\n')
			incomment = 0;
		if (!incomment)
			bare[j++] = raw[i];
	}
	bare[j] = '\0';
	OK("stripping comments left lines", j > 0, 1);
	OK("stripped is shorter", j < n, 1);
	parse(bare);
	OK("bare: nos", nos, 2);
	oks("bare: label 0", oslist[0].label, "OpenCoherent-3.5");
	OK("bare: timeout", cfgwait, 5);
	OK("bare: default", cfgdflt, 1);
	OK("bare: `flags SINGLE' still resolves", oslist[0].bflags, 1);
	OK("bare: nothing refused", oslist[0].badflg + oslist[1].badflg, 0);
	bflabel(0, fb, FLGSZ);
	oks("bare: named the same", fb, "SINGLE");
	cfglayout(0);
	OK("bare: hd4 blocks", bi.bi_part[4].bcount, 10200);
	OK("bare: hd15 blocks", bi.bi_part[15].bcount, 121856);
	OK("bare: slots named", nparts, 5);
	OK("bare: swapdev", bi.bi_swapdev, 3);
	OK("bare: swapbot", bi.bi_swapbot, 2904);
	OK("bare: swaptop", bi.bi_swaptop, 7000);
}

int
main()
{
	printf("cfgtest: the kboot.cfg parser\n");
	t_basic();
	t_v2keys();
	t_truncation();
	t_malformed();
	t_comments();
	t_layout();
	t_flags();
	t_system();
	t_sample();
	if (fails)
		printf("cfgtest: %d FAILED\n", fails);
	else
		printf("cfgtest: all passed\n");
	return fails != 0;
}
